### ISSUE TITLE
bottom navigatoin にerror

### ISSUE THREAD

**Issue by Naomath** [Naomath/EnglishFlashCards#12]
![image](https://user-images.githubusercontent.com/28499225/34252888-b4391a36-e688-11e7-992b-02926fc981ab.png)

上の写真のようにListのiconを選択しているのに青くならないし、アップされない

**Comment by halu5071** [comment]
![naoto](https://user-images.githubusercontent.com/18444125/34254249-93c25a00-e68e-11e7-9256-0868d6012e3b.gif)

とりあえずこの前貰ったコードだと、選択する部分はできてるね。

あと、押したときのFragmentの選択をする`OnNavigationItemSelectedListener`の実装はできてるんだけど、BottomNavigationViewにset出来てないね。

なので、findViewByIdでBottomNavigationViewを取得して、`setOnNavigationItemSelectedListener ()`を呼んであげればOK

参考 : 
https://qiita.com/oxsoft/items/daf7a13debfca8083d48
https://qiita.com/syamaoka/items/4d4054cd75df00460925

**Comment by halu5071** [comment]
動画を撮るソフトは、これ
https://github.com/mortenjust/androidtool-mac

**Comment by Naomath** [comment]
できました
