### ISSUE TITLE
Toolbarの戻る矢印にエラー

### ISSUE THREAD

**Issue by Naomath** [Naomath/EnglishFlashCards#18]
![image](https://user-images.githubusercontent.com/28499225/34482649-add71ee0-effc-11e7-9aab-f371f11ce7c5.png)
上の写真のように矢印をつけてもtouchが認識されない

**Comment by halu5071** [comment]
`AddWordActivity`の`settingToolbar()`で

```java
toolbar.setNavigationOnClickListener()
```
を使ってあげればOK

https://www.programcreek.com/java-api-examples/index.php?class=android.support.v7.widget.Toolbar&method=setNavigationOnClickListener

**Comment by Naomath** [comment]
codeを変えてやってみたが同じだった

**Comment by halu5071** [comment]
解決した。

いま、レイアウトがこうなってる

```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/relative_background"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.gotounaoto.myapplication.Activity.AddWordActivity">

    <android.support.v7.widget.Toolbar
        android:id="@+id/tool_bar"
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        android:theme="@style/ThemeOverlay.AppCompat.ActionBar"
        android:minHeight="?attr/actionBarSize"
        app:titleTextColor="@color/white"
        android:background="@color/colorTheme">
    </android.support.v7.widget.Toolbar>

</RelativeLayout>
```

それに対して、FragmentTransactionを用いて、AddWordActivity.javaの65行目から
```AddWordActivity.java
fragment = new AddWordsFragment();
FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
transaction.replace(R.id.relative_background, fragment);
transaction.commit();
```

と書いてる。

この`replace()`が全てのレイアウトを上書きしてしまってる。だからToolBarのコードが反映されてない。

なのでこうしてあげる。

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/relative_background"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context="com.example.gotounaoto.myapplication.Activity.AddWordActivity">

    <android.support.v7.widget.Toolbar
        android:id="@+id/tool_bar"
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        android:minHeight="?attr/actionBarSize"
        app:titleTextColor="@color/white"
        android:background="@color/colorTheme">
    </android.support.v7.widget.Toolbar>

    <LinearLayout
        android:id="@+id/layout_linear"
        android:layout_height="0dp"
        android:layout_width="match_parent"
        android:layout_weight="1">
    </LinearLayout>

</LinearLayout>
```
全体のレイアウトを`Linear`にして、`Linear`を追加。ここにFragmentをreplaceしてあげる。

```java
fragment = new AddWordsFragment();
FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
transaction.replace(R.id.layout_linear, fragment);
transaction.commit();
```

これで解決

**Comment by Naomath** [comment]
![image](https://user-images.githubusercontent.com/28499225/34485850-f87860ea-f00f-11e7-89b8-d161499dd9bc.png)

上の写真のようにタッチイベントの発生は認識できますが、メソッドの中身のfinishActivity();が実行されません。デバッグでも確認しました。

**Comment by halu5071** [comment]
理解

`setSupportActionBar(toolbar)`を、`setNavigationOnClickListener()`よりも上に書いて

**Comment by Naomath** [comment]
できました!!
ちなみになぜそうなるのですか？

**Comment by halu5071** [comment]
順番が大事なんよ

もともとActionBarっていうのがあったのだけど、Android5.0から ToolBarっていうのが代替として作られた。けどToolBarなんかに動作を定義したい場合には、ActionBarとして設定してあげる必要がある。

詳しく書くと結構かかるので、自分で調べてみて。コードを確認するのもいいよ。


参考までに、`setSupportActionBar()`のJavadocを一部訳しておく。（分かりやすさのために意訳）

> Set a {@link android.widget.Toolbar Toolbar} to act as the {@link android.support.v7.app.ActionBar} for this Activity window.
>
>  When set to a non-null value the {@link #getActionBar()} method will return an {@link android.support.v7.app.ActionBar} object that can be used to control the given toolbar as if it were a traditional window decor action bar. The toolbar's menu will be populated with the Activity's options menu and the navigation button will be wired through the standard {@link android.R.id#home home} menu select action.

> このアクティビティ画面に対し、ToolBarがActionBarとして振る舞うように設定します。
>
>  この引数でnullでない値が設定された場合、`getActionBar()` メソッドは、ActionBarオブジェクトを返します。このオブジェクトは特定のToolBarを、昔のバージョンの画面装飾をするActionBarのように制御するために使うことができます。このToolBarのメニューはアクティビティのオプションメニューに設定され、ナビゲーションボタンは標準の`R.id.home` メニューアクションに紐付けられます

**Comment by Naomath** [comment]
なるほどわかりました
