### ISSUE TITLE
[質問] toolbarとfragmentについて

### ISSUE THREAD

**Issue by Naomath** [Naomath/EnglishFlashCards#19]
MainActivityは現在BottomNagivatoinにより四つのfragmentに切り替えている。そしてそのfragmentごとにtoolbarの中身(検索ボタンをつけたり、menuをつけたり)変えたい。どうすべきか？

**Comment by Naomath** [comment]
toolbarはactivity_main.xmlが所持している。

**Comment by halu5071** [comment]
http://y-anz-m.blogspot.jp/2016/10/fragment-toolbar.html

これを参考に。
今回使いたいのは、見た目だけのToolBar**ではなく**、検索ボタンなどを実装するActionBarとして扱いたいので、Fragmentの`onCreateOptionMenu()`を使ってあげればいい

**Comment by Naomath** [comment]
なるほど。それを参考にしてやってみます！

**Comment by halu5071** [comment]
ちなみに検索画面には、そのものズバリの`SearchView`があるので挑戦してみるといいよ。
