### ISSUE TITLE
Fabの色について

### ISSUE THREAD

**Issue by Naomath** [Naomath/EnglishFlashCards#20]
![image](https://user-images.githubusercontent.com/28499225/34560698-34422824-f18a-11e7-9982-d7b8de2cb03d.png)
上の写真のfabのように周りがなぜか違う色になっている.

**Comment by halu5071** [comment]
いま、FABは

```xml
    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_marginBottom="16dp"
        android:layout_marginRight="16dp"
        android:backgroundTint="@color/colorTheme"
        android:src="@drawable/ic_add_white_48dp"
        app:elevation="6dp"
        app:fabSize="normal" />
```

となってるのだけど、ここの`backgroundTint`プロパティをこう書き換える

```xml
app:backgroundTint="@color/colorTheme"
```

xmlで使う「名前空間（namespace）」はいくつかあって、今回使いたい Floating Action Button に背景色を設定したいときには `app`名前空間を使ってあげる。

英語が読めるなら、ここを参考に。
https://stackoverflow.com/questions/26692233/what-is-the-app-android-xml-namespace

日本語記事はここかな。直接`app`については書かれてないけど、似たようなnamespaceの`tools`について書かれてる。
http://vividcode.hatenablog.com/entry/android-app/tools-attributes

**Comment by Naomath** [comment]
できました！
