### ISSUE TITLE
settinguserで設定できるもの

### ISSUE THREAD

**Issue by Naomath** [Naomath/EnglishFlashCards#28]
SettingUserFragmentで設定できるものについて

**Comment by Naomath** [comment]
ユーザー名
間違えやすい問題に登録されるライン、パーセンテージ

**Comment by halu5071** [comment]
アプリの設定画面を作る際には、
`com.android.support:preference-v14`を使うと便利

https://github.com/halu5071/conference-app-2018/blob/c2501af5040fbec7b028a40ad1f7b403ab8fb9ff/versions.gradle#L45
