### ISSUE TITLE
navigationbottomとfragment

### ISSUE THREAD

**Issue by Naomath** [Naomath/EnglishFlashCards#3]
navigationbottomがfragmentに遮られ表示されない
![image](https://user-images.githubusercontent.com/28499225/34079216-597ac794-e36c-11e7-9994-3a9040b02b2c.png)

**Comment by halu5071** [comment]
@Naomath 
最新のコードを見たいので、commit & push して欲しい

**Comment by Naomath** [comment]
コードは最新です
