### ISSUE TITLE
Firebaseのデータについて

### ISSUE THREAD

**Issue by Naomath** [Naomath/EnglishFlashCards#30]
一度アップロードしたデータを更新したり、消去したりできるようにする

**Comment by Naomath** [comment]
USERという枝にはそれぞれのuserにも単語帳があるが、それでは重くなってしまう。なのでその単語帳が保存してある場所まで飛べるような鍵を保存する

**Comment by halu5071** [comment]
```
.child("books").child(bookId)
```
で枝の移動はできる。([リファレンス「データの読み取りと書き込み」](https://firebase.google.com/docs/database/android/read-and-write?hl=ja#read_data_once))

ということは、BookのIDをどこかで知る必要がある。
なら、Userのデータの中にはBookのIDを持ってる必要があるね。

**Comment by Naomath** [comment]
やってみます!

**Comment by halu5071** [comment]
なので、Userの少し枝を改造する必要があるかも

```
users
|- user_one
    |- books
        |- book_id_one
        |- book_id_two
```

**Comment by Naomath** [comment]
そうですね
