### ISSUE TITLE
Out of Memory Errorが発生

### ISSUE THREAD

**Issue by Naomath** [Naomath/EnglishFlashCards#38]
<img width="1680" alt="2018-04-04 14 15 55" src="https://user-images.githubusercontent.com/28499225/38290066-5770dbda-3814-11e8-9b65-8acf5a975f6f.png">
<img width="1680" alt="2018-04-04 13 50 27" src="https://user-images.githubusercontent.com/28499225/38290067-58f4b99a-3814-11e8-9686-561f403febe8.png">
現在エラーが出ているのは下の写真でコメントアウトしているところだが、さらにいうとコメントアウトした状況で実行するとリストビューにitemがしっかりと表示されなくなっている。そのため直接的にMakeString.classに問題があるとは考えにくい。
<img width="1680" alt="2018-04-04 14 28 16" src="https://user-images.githubusercontent.com/28499225/38290131-bab1f954-3814-11e8-8c2c-4c374fe06983.png">

**Comment by Naomath** [comment]
![screenshot_1522819865](https://user-images.githubusercontent.com/28499225/38290172-f33fb0e0-3814-11e8-81ef-bac0774b73a3.png)

**Comment by Naomath** [comment]
ちなみにそのListVIewのitemの順番を変えても、コードの中で一番上に書いたものしか、正しく表示されなくなっている

**Comment by Naomath** [comment]
その後adapter自体にまず問題があることがわかった。二つ目のitem以降はなぜか反映されないのである。なのでMakeStringに問題があることが十分に考えられる。同時にadapterの原因究明も必要である。

**Comment by Naomath** [comment]
adapterの問題は解決した

**Comment by halu5071** [comment]
この問題は、`MakeString.java`の `makeStringWithComma()` の問題なので、デバッグモードでロジックを確認しておくこと
